"""
Provenance Guard — Flask API
Milestone 3: POST /submit (Signal 1 live, Signal 2 stub) + GET /log
"""

import uuid
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from dotenv import load_dotenv

from signal1_llm import classify_with_llm
import audit_log as db

load_dotenv()

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Rate limiting
# Limits chosen per planning.md rationale:
#   /submit     — 10/min: one creator submits one piece at a time
#   /appeal     — 3/min:  deliberate human action, prevent spam
#   /log        — 30/min: read-only but capped against scraping
# ---------------------------------------------------------------------------
limiter = Limiter(
    key_func=get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

db.init_db()


# ---------------------------------------------------------------------------
# Confidence scoring helpers
# ---------------------------------------------------------------------------

SIGNAL1_WEIGHT = 0.60
SIGNAL2_WEIGHT = 0.40


def combine_scores(s1: float, s2: float | None) -> float:
    """
    Weighted combination: 60% LLM signal + 40% stylometric signal.
    If Signal 2 is not yet available, fall back to Signal 1 only
    (used during M3 before the second signal is implemented).
    """
    if s2 is None:
        return round(s1, 4)
    return round(SIGNAL1_WEIGHT * s1 + SIGNAL2_WEIGHT * s2, 4)


def score_to_result(confidence: float) -> str:
    if confidence <= 0.35:
        return "ai"
    if confidence >= 0.80:
        return "human"
    return "uncertain"


def score_to_label(confidence: float) -> str:
    if confidence <= 0.35:
        return (
            "⚠️ Likely AI-Generated: Our analysis found strong signals that this content "
            "was produced with AI assistance. The author has not verified human authorship. "
            "This label reflects automated analysis and may not be fully accurate."
        )
    if confidence >= 0.80:
        return (
            "✅ Likely Human-Written: Our analysis found strong signals that this content "
            "was written by a human author. This label reflects automated analysis and is "
            "not a guarantee."
        )
    return (
        "🔍 Authorship Unclear: Our system could not confidently determine whether this "
        "content was written by a human or generated by AI. Treat this content with that "
        "uncertainty in mind. The creator may submit an appeal if this label is incorrect."
    )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute")
def submit():
    """
    POST /submit
    Body: { "content": "...", "creator_id": "optional" }
    Returns: submission_id, result, confidence, signal scores, label, status
    """
    body = request.get_json(silent=True)
    if not body or not body.get("content"):
        return jsonify({"error": "Request body must include a non-empty 'content' field."}), 400

    content: str = body["content"].strip()
    creator_id: str = body.get("creator_id", "")

    if len(content) < 20:
        return jsonify({"error": "Content is too short for meaningful analysis (minimum 20 characters)."}), 400

    submission_id = str(uuid.uuid4())

    # Signal 1 — LLM classification (live)
    signal1_score = classify_with_llm(content)

    # Signal 2 — stylometric heuristics (stub until M4)
    signal2_score = None  # will be replaced in Milestone 4

    confidence = combine_scores(signal1_score, signal2_score)
    result = score_to_result(confidence)
    label = score_to_label(confidence)

    db.log_submission(
        submission_id=submission_id,
        creator_id=creator_id,
        content=content,
        signal1_score=signal1_score,
        signal2_score=signal2_score,
        confidence=confidence,
        result=result,
        label=label,
    )

    return jsonify({
        "submission_id": submission_id,
        "result": result,
        "confidence": confidence,
        "signal1_score": signal1_score,
        "signal2_score": signal2_score,
        "label": label,
        "status": "reviewed",
    }), 200


@app.route("/log", methods=["GET"])
@limiter.limit("30 per minute")
def log():
    """
    GET /log
    Returns the most recent audit log entries.
    Query param: ?limit=N (default 50, max 100)
    """
    try:
        limit = min(int(request.args.get("limit", 50)), 100)
    except ValueError:
        limit = 50

    entries = db.get_log(limit=limit)
    return jsonify({"entries": entries, "count": len(entries)}), 200


# ---------------------------------------------------------------------------
# Placeholder routes — implemented in Milestone 5
# ---------------------------------------------------------------------------

@app.route("/appeal/<submission_id>", methods=["POST"])
@limiter.limit("3 per minute")
def appeal(submission_id):
    return jsonify({"message": "Appeal endpoint coming in Milestone 5."}), 501


@app.route("/appeals", methods=["GET"])
def appeals():
    return jsonify({"message": "Appeals listing coming in Milestone 5."}), 501


# ---------------------------------------------------------------------------
# Error handlers
# ---------------------------------------------------------------------------

@app.errorhandler(429)
def rate_limit_exceeded(e):
    return jsonify({"error": "Rate limit exceeded. Please slow down.", "details": str(e)}), 429


@app.errorhandler(404)
def not_found(e):
    return jsonify({"error": "Endpoint not found."}), 404


@app.errorhandler(500)
def internal_error(e):
    return jsonify({"error": "Internal server error.", "details": str(e)}), 500


if __name__ == "__main__":
    app.run(debug=True, port=5000)
