"""
Confidence Scoring — combines Signal 1 (LLM) and Signal 2 (stylometric)
Weights per planning.md: Signal 1 = 60%, Signal 2 = 40%

Thresholds (per planning.md Uncertainty Representation):
  confidence <= 0.35  →  result: 'ai'       label: Likely AI-Generated
  confidence 0.36–0.79 → result: 'uncertain' label: Authorship Unclear
  confidence >= 0.80  →  result: 'human'    label: Likely Human-Written
"""

SIGNAL1_WEIGHT = 0.60
SIGNAL2_WEIGHT = 0.40

# Label text — verbatim strings from planning.md and README
LABEL_AI = (
    "⚠️ Likely AI-Generated: Our analysis found strong signals that this content "
    "was produced with AI assistance. The author has not verified human authorship. "
    "This label reflects automated analysis and may not be fully accurate."
)

LABEL_UNCERTAIN = (
    "🔍 Authorship Unclear: Our system could not confidently determine whether this "
    "content was written by a human or generated by AI. Treat this content with that "
    "uncertainty in mind. The creator may submit an appeal if this label is incorrect."
)

LABEL_HUMAN = (
    "✅ Likely Human-Written: Our analysis found strong signals that this content "
    "was written by a human author. This label reflects automated analysis and is "
    "not a guarantee."
)


def combine_scores(signal1: float, signal2: float | None) -> float:
    """
    Weighted average of both signals.
    If signal2 is None (M3 fallback), returns signal1 only.
    """
    if signal2 is None:
        return round(signal1, 4)
    score = SIGNAL1_WEIGHT * signal1 + SIGNAL2_WEIGHT * signal2
    return round(score, 4)


def score_to_result(confidence: float) -> str:
    """Map combined confidence score to result string."""
    if confidence <= 0.35:
        return "ai"
    if confidence >= 0.80:
        return "human"
    return "uncertain"


def score_to_label(confidence: float) -> str:
    """Map combined confidence score to verbatim transparency label."""
    if confidence <= 0.35:
        return LABEL_AI
    if confidence >= 0.80:
        return LABEL_HUMAN
    return LABEL_UNCERTAIN
